<script setup lang="ts">
import { ref } from 'vue'
import HomeScreen from './components/HomeScreen.vue'
import QuestionFlow from './components/QuestionFlow.vue'
import QuestionMatch from './components/QuestionMatch.vue'
import type { Question, Answer, MatchAttempt } from './types/quiz'
import { samplePlayers, sampleQuestions, generateSampleAnswers } from './data/sampleData'

// Game phase tracking
type GamePhase = 'home' | 'lobby' | 'answering' | 'matching' | 'results'
const currentPhase = ref<GamePhase>('home')

// Game session data
const gameCode = ref<string>('')
const isHost = ref(false)

// Use sample data
const questions = sampleQuestions
const allAnswers = ref<Answer[]>(generateSampleAnswers())

// Current player info
const currentPlayer = ref({
  id: '',
  name: ''
})

// Track which question we're matching
const currentMatchQuestionIndex = ref(0)

// Store match results
const allMatchResults = ref<MatchAttempt[]>([])

// Store all submitted answers after completing the flow
const completedAnswers = ref<Answer[]>([])

/**
 * Handle creating a new game
 */
const handleCreateGame = (playerName: string) => {
  // Generate a random 6-character game code
  gameCode.value = Math.random().toString(36).substring(2, 8).toUpperCase()
  
  // Set player info
  currentPlayer.value = {
    id: 'player1', // Will be generated by server later
    name: playerName
  }
  
  isHost.value = true
  currentPhase.value = 'lobby'
  
  console.log('Game created with code:', gameCode.value)
  // TODO: Send to server to create game session
}

/**
 * Handle joining an existing game
 */
const handleJoinGame = (payload: { gameCode: string; playerName: string }) => {
  gameCode.value = payload.gameCode
  
  // Set player info
  currentPlayer.value = {
    id: `player_${Date.now()}`, // Will be generated by server later
    name: payload.playerName
  }
  
  isHost.value = false
  currentPhase.value = 'lobby'
  
  console.log('Joining game:', gameCode.value, 'as', payload.playerName)
  // TODO: Send to server to join game session
}

/**
 * Start the game (host only)
 */
const startGame = () => {
  currentPhase.value = 'answering'
  // TODO: Notify server to start game for all players
}

// Get current question for matching
const getCurrentMatchQuestion = () => questions[currentMatchQuestionIndex.value]

// Get answers for current question
const getCurrentQuestionAnswers = () => {
  const question = getCurrentMatchQuestion()
  return allAnswers.value.filter(a => a.questionId === question.id)
}

// Handle when the question flow is complete
const handleFlowComplete = (answers: Answer[]) => {
  completedAnswers.value = answers
  currentPhase.value = 'matching'
  console.log('All answers submitted:', answers)
}

// Handle match submission
const handleMatchSubmit = (attempts: MatchAttempt[]) => {
  allMatchResults.value.push(...attempts)
  console.log('Match results:', attempts)
  
  // Move to next question or finish
  if (currentMatchQuestionIndex.value < questions.length - 1) {
    setTimeout(() => {
      currentMatchQuestionIndex.value++
    }, 1500)
  } else {
    setTimeout(() => {
      currentPhase.value = 'results'
    }, 1500)
  }
}

// Reset to start over
const resetFlow = () => {
  completedAnswers.value = []
  currentPhase.value = 'home'
  currentMatchQuestionIndex.value = 0
  allMatchResults.value = []
  gameCode.value = ''
  isHost.value = false
  currentPlayer.value = { id: '', name: '' }
}

// Calculate total score
const calculateTotalScore = () => {
  const correct = allMatchResults.value.filter(m => m.isCorrect).length
  const total = allMatchResults.value.length
  return { correct, total }
}
</script>

<template>
  <div class="app">
    <!-- Home Screen -->
    <div v-if="currentPhase === 'home'" class="home-container">
      <HomeScreen
        @create-game="handleCreateGame"
        @join-game="handleJoinGame"
      />
    </div>

    <!-- Game Lobby -->
    <div v-else-if="currentPhase === 'lobby'" class="lobby-container">
      <div class="lobby-card">
        <h2>Game Lobby</h2>
        
        <div class="game-code-display">
          <label>Game Code</label>
          <div class="code">{{ gameCode }}</div>
          <p class="code-instruction">Share this code with other players</p>
        </div>

        <div class="player-info">
          <h3>Players</h3>
          <div class="player-list">
            <div class="player-item">
              <span class="player-name">{{ currentPlayer.name }}</span>
              <span v-if="isHost" class="host-badge">Host</span>
            </div>
            <!-- TODO: Show other players when they join -->
          </div>
        </div>

        <div class="lobby-actions">
          <button
            v-if="isHost"
            type="button"
            class="start-button"
            @click="startGame"
          >
            Start Game
          </button>
          <p v-else class="waiting-text">
            Waiting for host to start the game...
          </p>
        </div>

        <button
          type="button"
          class="leave-button"
          @click="resetFlow"
        >
          Leave Game
        </button>
      </div>
    </div>

    <!-- Game Phases -->
    <div v-else>
      <header class="app-header">
        <h1>Quiz App</h1>
        <div class="game-info">
          <span class="game-code-badge">Game: {{ gameCode }}</span>
          <span class="player-badge">{{ currentPlayer.name }}</span>
        </div>
        <p class="subtitle">
          <span v-if="currentPhase === 'answering'">Answer each question about yourself</span>
          <span v-else-if="currentPhase === 'matching'">Match answers to players</span>
          <span v-else>Final Results</span>
        </p>
      </header>

      <main class="app-main">
        <!-- Answering Phase -->
        <QuestionFlow
          v-if="currentPhase === 'answering'"
          :questions="questions"
          :player-id="currentPlayer.id"
          :player-name="currentPlayer.name"
          @complete="handleFlowComplete"
        />

        <!-- Matching Phase -->
        <div v-else-if="currentPhase === 'matching'" class="matching-section">
          <div class="progress-info">
            Question {{ currentMatchQuestionIndex + 1 }} of {{ questions.length }}
          </div>
          
          <QuestionMatch
            :key="getCurrentMatchQuestion().id"
            :question="getCurrentMatchQuestion()"
            :answers="getCurrentQuestionAnswers()"
            :players="samplePlayers"
            :current-player-id="currentPlayer.id"
            @submit="handleMatchSubmit"
          />
        </div>

        <!-- Results Phase -->
        <div v-else class="completion-section">
          <div class="completion-card">
            <h2>🎉 Quiz Complete!</h2>
            <p>Great job, {{ currentPlayer.name }}!</p>
            
            <div class="final-score">
              <div class="score-display">
                <span class="score-number">{{ calculateTotalScore().correct }}</span>
                <span class="score-divider">/</span>
                <span class="score-total">{{ calculateTotalScore().total }}</span>
              </div>
              <div class="score-label">Correct Matches</div>
              <div class="score-percentage">
                {{ Math.round((calculateTotalScore().correct / calculateTotalScore().total) * 100) }}%
              </div>
            </div>

            <button 
              type="button"
              class="reset-button"
              @click="resetFlow"
            >
              Back to Home
            </button>
          </div>
        </div>
      </main>
    </div>
  </div>
</template>

<style scoped>
.app {
  min-height: 100vh;
  background: linear-gradient(to bottom, #f5f5f5, #e9e9e9);
  padding: 2rem;
}

.home-container {
  min-height: 80vh;
  display: flex;
  align-items: center;
  justify-content: center;
}

.lobby-container {
  min-height: 80vh;
  display: flex;
  align-items: center;
  justify-content: center;
}

.lobby-card {
  max-width: 500px;
  width: 100%;
  background: white;
  padding: 2.5rem;
  border-radius: 16px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
}

.lobby-card h2 {
  margin: 0 0 2rem 0;
  color: #2c3e50;
  text-align: center;
  font-size: 1.75rem;
}

.game-code-display {
  text-align: center;
  margin-bottom: 2rem;
  padding: 1.5rem;
  background: linear-gradient(135deg, #f5f5f5, #e9e9e9);
  border-radius: 12px;
}

.game-code-display label {
  display: block;
  font-size: 0.875rem;
  color: #666;
  margin-bottom: 0.5rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.game-code-display .code {
  font-size: 2.5rem;
  font-weight: 700;
  color: #42b883;
  letter-spacing: 0.2em;
  font-family: 'Courier New', monospace;
}

.code-instruction {
  margin: 0.5rem 0 0 0;
  font-size: 0.875rem;
  color: #999;
}

.player-info {
  margin-bottom: 2rem;
}

.player-info h3 {
  margin: 0 0 1rem 0;
  color: #2c3e50;
  font-size: 1.125rem;
}

.player-list {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.player-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.875rem 1rem;
  background: #f9f9f9;
  border-radius: 8px;
  border-left: 4px solid #42b883;
}

.player-name {
  font-weight: 600;
  color: #2c3e50;
}

.host-badge {
  padding: 0.25rem 0.75rem;
  background: #42b883;
  color: white;
  border-radius: 12px;
  font-size: 0.75rem;
  font-weight: 600;
}

.lobby-actions {
  margin-bottom: 1rem;
}

.start-button {
  width: 100%;
  padding: 1rem;
  font-size: 1.125rem;
  font-weight: 600;
  color: white;
  background: #42b883;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.3s;
}

.start-button:hover {
  background: #35a372;
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(66, 184, 131, 0.3);
}

.waiting-text {
  text-align: center;
  color: #666;
  font-style: italic;
  margin: 0;
  padding: 1rem;
}

.leave-button {
  width: 100%;
  padding: 0.75rem;
  font-size: 0.95rem;
  color: #e74c3c;
  background: transparent;
  border: 2px solid #e74c3c;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.3s;
}

.leave-button:hover {
  background: #e74c3c;
  color: white;
}

.app-header {
  text-align: center;
  margin-bottom: 2rem;
}

.app-header h1 {
  color: #2c3e50;
  font-size: 2rem;
  font-weight: 700;
  margin: 0;
}

.game-info {
  display: flex;
  justify-content: center;
  gap: 1rem;
  margin: 0.75rem 0;
}

.game-code-badge, .player-badge {
  padding: 0.375rem 0.875rem;
  background: white;
  border-radius: 16px;
  font-size: 0.875rem;
  font-weight: 600;
  color: #666;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.game-code-badge {
  color: #42b883;
}

.subtitle {
  margin: 0.5rem 0 0 0;
  color: #666;
  font-size: 1rem;
}

.app-main {
  display: flex;
  flex-direction: column;
  gap: 2rem;
}

.matching-section {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.progress-info {
  text-align: center;
  font-size: 0.875rem;
  font-weight: 500;
  color: #666;
  padding: 0.5rem;
  background: white;
  border-radius: 8px;
  max-width: 800px;
  margin: 0 auto;
}

.completion-section {
  display: flex;
  justify-content: center;
}

.completion-card {
  max-width: 600px;
  width: 100%;
  padding: 2rem;
  background: white;
  border-radius: 12px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  text-align: center;
}

.completion-card h2 {
  color: #2c3e50;
  margin: 0 0 1rem 0;
  font-size: 1.75rem;
}

.completion-card > p {
  color: #666;
  margin: 0 0 2rem 0;
}

.final-score {
  margin: 2rem 0;
  padding: 2rem;
  background: linear-gradient(135deg, #f5f5f5, #e9e9e9);
  border-radius: 12px;
}

.score-display {
  font-size: 4rem;
  font-weight: 700;
  color: #42b883;
  margin-bottom: 0.5rem;
}

.score-number {
  color: #42b883;
}

.score-divider {
  color: #ccc;
  margin: 0 0.5rem;
}

.score-total {
  color: #666;
}

.score-label {
  font-size: 1.125rem;
  color: #666;
  margin-bottom: 1rem;
}

.score-percentage {
  font-size: 2rem;
  font-weight: 600;
  color: #2c3e50;
}

.reset-button {
  padding: 0.75rem 2rem;
  font-size: 1rem;
  font-weight: 500;
  color: white;
  background: #42b883;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  transition: background 0.3s;
}

.reset-button:hover {
  background: #35a372;
}
</style>

